name: "SSH-Game"
services:
  ssh-server:
    build: .
    image: ghcr.io/byteingpython/ssh-game
    ports:
      - "2022:2022"
    environment:
      REDIS_HOST: "keydb"
      REDIS_PORT: 6379
      SSH_PORT: 2022
      SURREALDB_HOST: "surrealdb"
      SURREALDB_PORT: "8000"
      SURREALDB_USER: "root"
      SURREALDB_PASSWORD: "<change-me>"
      # Set this if you want a consistent host key. For more information on generating such a keypair, see the README.
      # SSH_PRIVATE_KEY: ""
      # SSH_PUBLIC_KEY: ""
  surrealdb:
    pull_policy: always
    user: "root"
    volumes:
      - ./data:/data
    image: surrealdb/surrealdb:latest
    command: start file:/data/surrealdb.db
    environment:
      SURREAL_USER: "root"
      SURREAL_PASS: "<change-me>"
  keydb:
    image: eqalpha/keydb